# runs on feature branch pushes, runs fast unit and integration tests
name: feature_push_test
on:
  push:
    branches:
      - 'feat-*'
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
# for speed of unit tests and coverage we'de doing this outside of a docker build
# this could lead to what is shipped not being what is tested
    - name: Setup
      run: |
        pip install poetry
        poetry install
    - name: Run unit tests
      run: poetry run coverage run -m pytest tests/test_unit.py
    - name: check coverage
      run: poetry run coverage report --fail-under 90