# runs on all branches, runs the tests, ships to a temp environment
name: FeatureCI
on:
  push:
    branches:
      - '*'
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
# for speed of unit tests and coverage we'de doing this outside of a docker build
# this could lead to what is shipped not being what is tested
    - name: Setup
      run: |
        pip install poetry
        poetry install
    - name: Run unit tests
      run: poetry run coverage run -m pytest tests/test_unit.py
    - name: check coverage
      run: poetry run coverage report --fail-under 90
# If the tests pass we'll do a build in docker      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.my_key }}
        aws-secret-access-key: ${{ secrets.my_secret }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: sentinel_test
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG